apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-app
  namespace: taskmanager
  labels:
    app: taskmanager-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmanager-app
  template:
    metadata:
      labels:
        app: taskmanager-app
    spec:
      containers:
        - name: taskmanager-container
          image: nexus.imcc.com/repository/docker-repo/taskmanager-webapp:11  # Use the tag from Jenkins build
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: taskmanager-secret
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: taskmanager-secret
                  key: JWT_SECRET
      imagePullSecrets:
        - name: nexus-secret
